PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

FIELD !P_ISIN MODULE %_P_ISIN .

FIELD !P_FILE MODULE %_P_FILE .

FIELD !P_AGG MODULE %_P_AGG .

CHAIN.
  FIELD P_ISIN .
  FIELD P_FILE .
  FIELD P_AGG .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.

PROCESS ON VALUE-REQUEST.
  FIELD P_FILE MODULE %_P_FILE_VAL .